<div class="field comment">
    <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('Comment') ?></span></label>
    <div class="control">
        <input type="text" name="comment" value="<?php echo $block->getCommentValue() ?>" title="<?php /* @escapeNotVerified */ echo __('Comment') ?>" id="comment" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Enter a comment') ?>">
    </div>
</div>